# Generated by Django 4.2.6 on 2023-10-17 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text="Une ID unique pour chaque formulaire de l'app", primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('responses', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(verbose_name='Date de création')),
            ],
        ),
    ]
